# Generated by Django 5.1.7 on 2025-06-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('inn', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ИНН организации')),
                ('balance', models.PositiveIntegerField(verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['inn'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('organization_balance_before', models.PositiveIntegerField(verbose_name='Баланс до изменения')),
                ('organization_balance_after', models.PositiveIntegerField(verbose_name='Баланс после изменения')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_logs', to='organizations.organization', verbose_name='Организация')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='operations.payment', verbose_name='Платежный документ')),
            ],
            options={
                'verbose_name': 'Лог платежа',
                'verbose_name_plural': 'Логи платежей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='organizatio_organiz_02d03e_idx'), models.Index(fields=['payment'], name='organizatio_payment_2aaf76_idx')],
            },
        ),
    ]
