# Generated by Django 5.1.7 on 2025-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ИНН организации'),
        ),
    ]
