# Generated by Django 5.1.7 on 2025-06-04 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID операции')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('payer_inn', models.CharField(max_length=12, verbose_name='ИНН плательщика')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('document_date', models.DateTimeField(verbose_name='Дата документа')),
            ],
            options={
                'verbose_name': 'Платежный документ',
                'verbose_name_plural': 'Платежные документы',
                'ordering': ['-document_date'],
            },
        ),
    ]
