# Generated by Django 5.1.7 on 2025-06-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_payment_operation_id'),
        ('organizations', '0002_alter_organization_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer_inn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='ИНН плательщика'),
        ),
    ]
